#!/bin/sh

# =========================================================================
# title           : maj
# description     : MAJ pour flemmard
# author          : mathieu[@]400iso[.]net
# date            : 
# version         : 0.1    
# usage           : just run it
# notes           : 
# Licence         : WTFPL-2 // http://www.wtfpl.net/txt/copying/ 
# =========================================================================

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove;
exit;
